development:
  adapter: postgresql
  encoding: unicode
  database: therobotrade_development
  host: localhost
  pool: 20
  #username: therobotrade
  #password: 

test:
  adapter: postgresql
  encoding: unicode
  database: therobotrade_test
  host: localhost
  pool: 20
  #username: therobotrade
  #password:

production:
  adapter: postgresql
  encoding: unicode
  database: therobotrade_production
  host: localhost
  pool: 20
  username: therobotrade
  password:
